//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/metcalfe/service/ContributorMapper.java
//

#ifndef _ContributorMapper_H_
#define _ContributorMapper_H_

#include "J2ObjC_header.h"

@protocol JavaUtilList;

/**
 @brief Created by alex on 12/07/15.
 */
@interface ContributorMapper : NSObject

#pragma mark Public

- (instancetype)init;

- (id<JavaUtilList>)mapAllWithNSString:(NSString *)json;

@end

J2OBJC_EMPTY_STATIC_INIT(ContributorMapper)

FOUNDATION_EXPORT void ContributorMapper_init(ContributorMapper *self);

FOUNDATION_EXPORT ContributorMapper *new_ContributorMapper_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ContributorMapper)

typedef ContributorMapper ComMetcalfeServiceContributorMapper;

#endif // _ContributorMapper_H_
