//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/metcalfe/model/Contributor.java
//


#line 1 "src/main/java/com/metcalfe/model/Contributor.java"

#include "Contributor.h"
#include "J2ObjC_source.h"

@interface Contributor () {
 @public
  NSString *login_;
  jint contributions_;
}

@end

J2OBJC_FIELD_SETTER(Contributor, login_, NSString *)


#line 6
@implementation Contributor


#line 11
- (instancetype)initWithNSString:(NSString *)login
                         withInt:(jint)contributions {
  Contributor_initWithNSString_withInt_(self, login, contributions);
  return self;
}


#line 16
- (NSString *)getLogin {
  return login_;
}

- (jint)getContributions {
  return contributions_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withInt:", "Contributor", NULL, 0x1, NULL, NULL },
    { "getLogin", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getContributions", NULL, "I", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "login_", NULL, 0x12, "Ljava.lang.String;", NULL, NULL,  },
    { "contributions_", NULL, 0x12, "I", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _Contributor = { 2, "Contributor", "com.metcalfe.model", NULL, 0x1, 3, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_Contributor;
}

@end


#line 11
void Contributor_initWithNSString_withInt_(Contributor *self, NSString *login, jint contributions) {
  (void) NSObject_init(self);
  
#line 12
  self->login_ = login;
  self->contributions_ = contributions;
}


#line 11
Contributor *new_Contributor_initWithNSString_withInt_(NSString *login, jint contributions) {
  Contributor *self = [Contributor alloc];
  Contributor_initWithNSString_withInt_(self, login, contributions);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Contributor)
