//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/metcalfe/service/ContributorMapper.java
//


#line 1 "src/main/java/com/metcalfe/service/ContributorMapper.java"

#include "ContributorMapper.h"
#include "Gson.h"
#include "J2ObjC_source.h"
#include "TypeToken.h"
#include "java/lang/reflect/Type.h"
#include "java/util/List.h"

@interface ContributorMapper_$1 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ContributorMapper_$1)

__attribute__((unused)) static void ContributorMapper_$1_init(ContributorMapper_$1 *self);

__attribute__((unused)) static ContributorMapper_$1 *new_ContributorMapper_$1_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ContributorMapper_$1)


#line 12
@implementation ContributorMapper

- (id<JavaUtilList>)mapAllWithNSString:(NSString *)json {
  return [new_ComGoogleGsonGson_init() fromJsonWithNSString:json withJavaLangReflectType:
#line 16
  [new_ContributorMapper_$1_init() getType]];
}

- (instancetype)init {
  ContributorMapper_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "mapAllWithNSString:", "mapAll", "Ljava.util.List;", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _ContributorMapper = { 2, "ContributorMapper", "com.metcalfe.service", NULL, 0x1, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ContributorMapper;
}

@end

void ContributorMapper_init(ContributorMapper *self) {
  (void) NSObject_init(self);
}

ContributorMapper *new_ContributorMapper_init() {
  ContributorMapper *self = [ContributorMapper alloc];
  ContributorMapper_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ContributorMapper)

@implementation ContributorMapper_$1

- (instancetype)init {
  ContributorMapper_$1_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "", NULL, 0x0, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.util.List;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ContributorMapper", "mapAllWithNSString:" };
  static const J2ObjcClassInfo _ContributorMapper_$1 = { 2, "", "com.metcalfe.service", "ContributorMapper", 0x8008, 1, methods, 0, NULL, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/reflect/TypeToken<Ljava/util/List<Lcom/metcalfe/model/Contributor;>;>;" };
  return &_ContributorMapper_$1;
}

@end

void ContributorMapper_$1_init(ContributorMapper_$1 *self) {
  (void) ComGoogleGsonReflectTypeToken_init(self);
}

ContributorMapper_$1 *new_ContributorMapper_$1_init() {
  ContributorMapper_$1 *self = [ContributorMapper_$1 alloc];
  ContributorMapper_$1_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ContributorMapper_$1)
