//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/ExclusionStrategy.java
//


#line 1 "jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/ExclusionStrategy.java"

#include "ExclusionStrategy.h"
#include "FieldAttributes.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"

@interface ComGoogleGsonExclusionStrategy : NSObject
@end


#line 96
@implementation ComGoogleGsonExclusionStrategy

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "shouldSkipFieldWithComGoogleGsonFieldAttributes:", "shouldSkipField", "Z", 0x401, NULL, NULL },
    { "shouldSkipClassWithIOSClass:", "shouldSkipClass", "Z", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComGoogleGsonExclusionStrategy = { 2, "ExclusionStrategy", "com.google.gson", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonExclusionStrategy;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComGoogleGsonExclusionStrategy)
