//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/FieldNamingStrategy.java
//

#ifndef _ComGoogleGsonFieldNamingStrategy_H_
#define _ComGoogleGsonFieldNamingStrategy_H_

#include "J2ObjC_header.h"

@class JavaLangReflectField;

/**
 @brief A mechanism for providing custom field naming in Gson.
 This allows the client code to translate field names into a particular convention that is not supported as a normal Java field declaration rules.  For example, Java does not support "-" characters in a field name.
 @author Inderjeet Singh
 @author Joel Leitch
 @since 1.3
 */
@protocol ComGoogleGsonFieldNamingStrategy < NSObject, JavaObject >

/**
 @brief Translates the field name into its JSON field name representation.
 @param f the field object that we are translating
 @return the translated field name.
 @since 1.3
 */
- (NSString *)translateNameWithJavaLangReflectField:(JavaLangReflectField *)f;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFieldNamingStrategy)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFieldNamingStrategy)

#endif // _ComGoogleGsonFieldNamingStrategy_H_
