//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/metcalfe/service/GitHubService.java
//


#line 1 "src/main/java/com/metcalfe/service/GitHubService.java"

#include "GitHubService.h"
#include "J2ObjC_source.h"
#include "java/util/List.h"

@interface GitHubService : NSObject
@end


#line 10
@implementation GitHubService

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "contributors", NULL, "Ljava.util.List;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _GitHubService = { 2, "GitHubService", "com.metcalfe.service", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_GitHubService;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GitHubService)
