//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/metcalfe/service/GitHubService.java
//

#ifndef _GitHubService_H_
#define _GitHubService_H_

#include "J2ObjC_header.h"

@protocol JavaUtilList;

/**
 @brief Created by alex on 12/07/15.
 */
@protocol GitHubService < NSObject, JavaObject >

- (id<JavaUtilList>)contributors;

@end

J2OBJC_EMPTY_STATIC_INIT(GitHubService)

J2OBJC_TYPE_LITERAL_HEADER(GitHubService)

#define ComMetcalfeServiceGitHubService GitHubService

#endif // _GitHubService_H_
