//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/metcalfe/service/HttpClient.java
//

#ifndef _HttpClient_H_
#define _HttpClient_H_

#include "J2ObjC_header.h"

/**
 @brief Created by alex on 12/07/15.
 */
@protocol HttpClient < NSObject, JavaObject >

- (NSString *)performGetWithNSString:(NSString *)getUrl;

@end

J2OBJC_EMPTY_STATIC_INIT(HttpClient)

J2OBJC_TYPE_LITERAL_HEADER(HttpClient)

#define ComMetcalfeServiceHttpClient HttpClient

#endif // _HttpClient_H_
