//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/metcalfe/service/HttpClient.java
//


#line 1 "src/main/java/com/metcalfe/service/HttpClient.java"

#include "HttpClient.h"
#include "J2ObjC_source.h"

@interface HttpClient : NSObject
@end


#line 6
@implementation HttpClient

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "performGetWithNSString:", "performGet", "Ljava.lang.String;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _HttpClient = { 2, "HttpClient", "com.metcalfe.service", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_HttpClient;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(HttpClient)
