//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/InstanceCreator.java
//


#line 1 "jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/InstanceCreator.java"

#include "InstanceCreator.h"
#include "J2ObjC_source.h"
#include "java/lang/reflect/Type.h"

@interface ComGoogleGsonInstanceCreator : NSObject
@end


#line 79
@implementation ComGoogleGsonInstanceCreator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createInstanceWithJavaLangReflectType:", "createInstance", "TT;", 0x401, NULL, "(Ljava/lang/reflect/Type;)TT;" },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInstanceCreator = { 2, "InstanceCreator", "com.google.gson", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_ComGoogleGsonInstanceCreator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComGoogleGsonInstanceCreator)
