//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/internal/JsonReaderInternalAccess.java
//

#ifndef _ComGoogleGsonInternalJsonReaderInternalAccess_H_
#define _ComGoogleGsonInternalJsonReaderInternalAccess_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonStreamJsonReader;

/**
 @brief Internal-only APIs of JsonReader available only to other classes in Gson.
 */
@interface ComGoogleGsonInternalJsonReaderInternalAccess : NSObject

#pragma mark Public

- (instancetype)init;

/**
 @brief Changes the type of the current property name token to a string value.
 */
- (void)promoteNameToValueWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalJsonReaderInternalAccess)

FOUNDATION_EXPORT ComGoogleGsonInternalJsonReaderInternalAccess *ComGoogleGsonInternalJsonReaderInternalAccess_INSTANCE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonInternalJsonReaderInternalAccess, INSTANCE_, ComGoogleGsonInternalJsonReaderInternalAccess *)
J2OBJC_STATIC_FIELD_SETTER(ComGoogleGsonInternalJsonReaderInternalAccess, INSTANCE_, ComGoogleGsonInternalJsonReaderInternalAccess *)

FOUNDATION_EXPORT void ComGoogleGsonInternalJsonReaderInternalAccess_init(ComGoogleGsonInternalJsonReaderInternalAccess *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalJsonReaderInternalAccess)

#endif // _ComGoogleGsonInternalJsonReaderInternalAccess_H_
