//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/JsonDeserializationContext.java
//

#ifndef _ComGoogleGsonJsonDeserializationContext_H_
#define _ComGoogleGsonJsonDeserializationContext_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonJsonElement;
@protocol JavaLangReflectType;

/**
 @brief Context for deserialization that is passed to a custom deserializer during invocation of its JsonDeserializer#deserialize(JsonElement,Type,JsonDeserializationContext) method.
 @author Inderjeet Singh
 @author Joel Leitch
 */
@protocol ComGoogleGsonJsonDeserializationContext < NSObject, JavaObject >

/**
 @brief Invokes default deserialization on the specified object.
 It should never be invoked on the element received as a parameter of the JsonDeserializer#deserialize(JsonElement,Type,JsonDeserializationContext) method. Doing so will result in an infinite loop since Gson will in-turn call the custom deserializer again.
 @param json the parse tree.
 @param typeOfT type of the expected return value.
 @param < T > The type of the deserialized object.
 @return An object of type typeOfT.
 @throws JsonParseException if the parse tree does not contain expected data.
 */
- (id)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonDeserializationContext)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonDeserializationContext)

#endif // _ComGoogleGsonJsonDeserializationContext_H_
