//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/JsonIOException.java
//

#ifndef _ComGoogleGsonJsonIOException_H_
#define _ComGoogleGsonJsonIOException_H_

#include "J2ObjC_header.h"
#include "JsonParseException.h"

@class JavaLangThrowable;

/**
 @brief This exception is raised when Gson was unable to read an input stream or write to one.
 @author Inderjeet Singh
 @author Joel Leitch
 */
@interface ComGoogleGsonJsonIOException : ComGoogleGsonJsonParseException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)cause;

/**
 @brief Creates exception with the specified cause.
 Consider using #JsonIOException(String,Throwable) instead if you can describe what happened.
 @param cause root exception that caused this exception to be thrown.
 */
- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonIOException)

FOUNDATION_EXPORT void ComGoogleGsonJsonIOException_initWithNSString_(ComGoogleGsonJsonIOException *self, NSString *msg);

FOUNDATION_EXPORT ComGoogleGsonJsonIOException *new_ComGoogleGsonJsonIOException_initWithNSString_(NSString *msg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonJsonIOException_initWithNSString_withJavaLangThrowable_(ComGoogleGsonJsonIOException *self, NSString *msg, JavaLangThrowable *cause);

FOUNDATION_EXPORT ComGoogleGsonJsonIOException *new_ComGoogleGsonJsonIOException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonJsonIOException_initWithJavaLangThrowable_(ComGoogleGsonJsonIOException *self, JavaLangThrowable *cause);

FOUNDATION_EXPORT ComGoogleGsonJsonIOException *new_ComGoogleGsonJsonIOException_initWithJavaLangThrowable_(JavaLangThrowable *cause) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonIOException)

#endif // _ComGoogleGsonJsonIOException_H_
