//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/JsonObject.java
//

#ifndef _ComGoogleGsonJsonObject_H_
#define _ComGoogleGsonJsonObject_H_

#include "J2ObjC_header.h"
#include "JsonElement.h"

@class ComGoogleGsonJsonArray;
@class ComGoogleGsonJsonPrimitive;
@class JavaLangBoolean;
@class JavaLangCharacter;
@protocol JavaUtilSet;

/**
 @brief A class representing an object type in Json.
 An object consists of name-value pairs where names are strings, and values are any other type of JsonElement . This allows for a creating a tree of JsonElements. The member elements of this object are maintained in order they were added.
 @author Inderjeet Singh
 @author Joel Leitch
 */
@interface ComGoogleGsonJsonObject : ComGoogleGsonJsonElement

#pragma mark Public

- (instancetype)init;

/**
 @brief Adds a member, which is a name-value pair, to self.
 The name must be a String, but the value can be an arbitrary JsonElement, thereby allowing you to build a full tree of JsonElements rooted at this node.
 @param property name of the member.
 @param value the member object.
 */
- (void)addWithNSString:(NSString *)property
withComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)value;

/**
 @brief Convenience method to add a boolean member.
 The specified value is converted to a JsonPrimitive of Boolean.
 @param property name of the member.
 @param value the number value associated with the member.
 */
- (void)addPropertyWithNSString:(NSString *)property
            withJavaLangBoolean:(JavaLangBoolean *)value;

/**
 @brief Convenience method to add a char member.
 The specified value is converted to a JsonPrimitive of Character.
 @param property name of the member.
 @param value the number value associated with the member.
 */
- (void)addPropertyWithNSString:(NSString *)property
          withJavaLangCharacter:(JavaLangCharacter *)value;

/**
 @brief Convenience method to add a primitive member.
 The specified value is converted to a JsonPrimitive of Number.
 @param property name of the member.
 @param value the number value associated with the member.
 */
- (void)addPropertyWithNSString:(NSString *)property
                   withNSNumber:(NSNumber *)value;

/**
 @brief Convenience method to add a primitive member.
 The specified value is converted to a JsonPrimitive of String.
 @param property name of the member.
 @param value the string value associated with the member.
 */
- (void)addPropertyWithNSString:(NSString *)property
                   withNSString:(NSString *)value;

/**
 @brief Returns a set of members of this object.
 The set is ordered, and the order is in which the elements were added.
 @return a set of members of this object.
 */
- (id<JavaUtilSet>)entrySet;

- (jboolean)isEqual:(id)o;

/**
 @brief Returns the member with the specified name.
 @param memberName name of the member that is being requested.
 @return the member matching the name. Null if no such member exists.
 */
- (ComGoogleGsonJsonElement *)getWithNSString:(NSString *)memberName;

/**
 @brief Convenience method to get the specified member as a JsonArray.
 @param memberName name of the member being requested.
 @return the JsonArray corresponding to the specified member.
 */
- (ComGoogleGsonJsonArray *)getAsJsonArrayWithNSString:(NSString *)memberName;

/**
 @brief Convenience method to get the specified member as a JsonObject.
 @param memberName name of the member being requested.
 @return the JsonObject corresponding to the specified member.
 */
- (ComGoogleGsonJsonObject *)getAsJsonObjectWithNSString:(NSString *)memberName;

/**
 @brief Convenience method to get the specified member as a JsonPrimitive element.
 @param memberName name of the member being requested.
 @return the JsonPrimitive corresponding to the specified member.
 */
- (ComGoogleGsonJsonPrimitive *)getAsJsonPrimitiveWithNSString:(NSString *)memberName;

/**
 @brief Convenience method to check if a member with the specified name is present in this object.
 @param memberName name of the member that is being checked for presence.
 @return true if there is a member with the specified name, false otherwise.
 */
- (jboolean)hasWithNSString:(NSString *)memberName;

- (NSUInteger)hash;

/**
 @brief Removes the <code>property</code> from this JsonObject .
 @param property name of the member that should be removed.
 @return the JsonElement object that is being removed.
 @since 1.3
 */
- (ComGoogleGsonJsonElement *)removeWithNSString:(NSString *)property;

#pragma mark Package-Private

- (ComGoogleGsonJsonObject *)deepCopy;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonObject)

FOUNDATION_EXPORT void ComGoogleGsonJsonObject_init(ComGoogleGsonJsonObject *self);

FOUNDATION_EXPORT ComGoogleGsonJsonObject *new_ComGoogleGsonJsonObject_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonObject)

#endif // _ComGoogleGsonJsonObject_H_
