//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/internal/bind/JsonTreeWriter.java
//

#ifndef _ComGoogleGsonInternalBindJsonTreeWriter_H_
#define _ComGoogleGsonInternalBindJsonTreeWriter_H_

#include "J2ObjC_header.h"
#include "JsonWriter.h"

@class ComGoogleGsonJsonElement;

/**
 @brief This writer creates a JsonElement.
 */
@interface ComGoogleGsonInternalBindJsonTreeWriter : ComGoogleGsonStreamJsonWriter

#pragma mark Public

- (instancetype)init;

- (ComGoogleGsonStreamJsonWriter *)beginArray;

- (ComGoogleGsonStreamJsonWriter *)beginObject;

- (void)close;

- (ComGoogleGsonStreamJsonWriter *)endArray;

- (ComGoogleGsonStreamJsonWriter *)endObject;

- (void)flush;

/**
 @brief Returns the top level object produced by this writer.
 */
- (ComGoogleGsonJsonElement *)get;

- (ComGoogleGsonStreamJsonWriter *)nameWithNSString:(NSString *)name;

- (ComGoogleGsonStreamJsonWriter *)nullValue;

- (ComGoogleGsonStreamJsonWriter *)valueWithBoolean:(jboolean)value;

- (ComGoogleGsonStreamJsonWriter *)valueWithDouble:(jdouble)value;

- (ComGoogleGsonStreamJsonWriter *)valueWithLong:(jlong)value;

- (ComGoogleGsonStreamJsonWriter *)valueWithNSNumber:(NSNumber *)value;

- (ComGoogleGsonStreamJsonWriter *)valueWithNSString:(NSString *)value;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonInternalBindJsonTreeWriter)

FOUNDATION_EXPORT void ComGoogleGsonInternalBindJsonTreeWriter_init(ComGoogleGsonInternalBindJsonTreeWriter *self);

FOUNDATION_EXPORT ComGoogleGsonInternalBindJsonTreeWriter *new_ComGoogleGsonInternalBindJsonTreeWriter_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindJsonTreeWriter)

#endif // _ComGoogleGsonInternalBindJsonTreeWriter_H_
