//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/JsonParseException.java
//


#line 1 "jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/JsonParseException.java"

#include "J2ObjC_source.h"
#include "JsonParseException.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/Throwable.h"


#line 32
@implementation ComGoogleGsonJsonParseException


#line 41
- (instancetype)initWithNSString:(NSString *)msg {
  ComGoogleGsonJsonParseException_initWithNSString_(self, msg);
  return self;
}


#line 51
- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)cause {
  ComGoogleGsonJsonParseException_initWithNSString_withJavaLangThrowable_(self, msg, cause);
  return self;
}


#line 61
- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause {
  ComGoogleGsonJsonParseException_initWithJavaLangThrowable_(self, cause);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "JsonParseException", NULL, 0x1, NULL, NULL },
    { "initWithNSString:withJavaLangThrowable:", "JsonParseException", NULL, 0x1, NULL, NULL },
    { "initWithJavaLangThrowable:", "JsonParseException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x18, "J", NULL, NULL, .constantValue.asLong = ComGoogleGsonJsonParseException_serialVersionUID },
  };
  static const J2ObjcClassInfo _ComGoogleGsonJsonParseException = { 2, "JsonParseException", "com.google.gson", NULL, 0x1, 3, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonJsonParseException;
}

@end


#line 41
void ComGoogleGsonJsonParseException_initWithNSString_(ComGoogleGsonJsonParseException *self, NSString *msg) {
  (void) JavaLangRuntimeException_initWithNSString_(self, msg);
}


#line 41
ComGoogleGsonJsonParseException *new_ComGoogleGsonJsonParseException_initWithNSString_(NSString *msg) {
  ComGoogleGsonJsonParseException *self = [ComGoogleGsonJsonParseException alloc];
  ComGoogleGsonJsonParseException_initWithNSString_(self, msg);
  return self;
}


#line 51
void ComGoogleGsonJsonParseException_initWithNSString_withJavaLangThrowable_(ComGoogleGsonJsonParseException *self, NSString *msg, JavaLangThrowable *cause) {
  (void) JavaLangRuntimeException_initWithNSString_withJavaLangThrowable_(self, msg, cause);
}


#line 51
ComGoogleGsonJsonParseException *new_ComGoogleGsonJsonParseException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause) {
  ComGoogleGsonJsonParseException *self = [ComGoogleGsonJsonParseException alloc];
  ComGoogleGsonJsonParseException_initWithNSString_withJavaLangThrowable_(self, msg, cause);
  return self;
}


#line 61
void ComGoogleGsonJsonParseException_initWithJavaLangThrowable_(ComGoogleGsonJsonParseException *self, JavaLangThrowable *cause) {
  (void) JavaLangRuntimeException_initWithJavaLangThrowable_(self, cause);
}


#line 61
ComGoogleGsonJsonParseException *new_ComGoogleGsonJsonParseException_initWithJavaLangThrowable_(JavaLangThrowable *cause) {
  ComGoogleGsonJsonParseException *self = [ComGoogleGsonJsonParseException alloc];
  ComGoogleGsonJsonParseException_initWithJavaLangThrowable_(self, cause);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonJsonParseException)
