//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/JsonObject.java
//


#line 1 "jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/JsonObject.java"

#include "J2ObjC_source.h"
#include "JsonArray.h"
#include "JsonElement.h"
#include "JsonNull.h"
#include "JsonObject.h"
#include "JsonPrimitive.h"
#include "LinkedTreeMap.h"
#include "java/lang/Boolean.h"
#include "java/lang/Character.h"
#include "java/util/Map.h"
#include "java/util/Set.h"

@interface ComGoogleGsonJsonObject () {
 @public
  ComGoogleGsonInternalLinkedTreeMap *members_;
}

/**
 @brief Creates the proper JsonElement object from the given <code>value</code> object.
 @param value the object to generate the JsonElement for
 @return a JsonPrimitive if the <code>value</code> is not null, otherwise a JsonNull
 */
- (ComGoogleGsonJsonElement *)createJsonElementWithId:(id)value;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonJsonObject, members_, ComGoogleGsonInternalLinkedTreeMap *)

__attribute__((unused)) static ComGoogleGsonJsonElement *ComGoogleGsonJsonObject_createJsonElementWithId_(ComGoogleGsonJsonObject *self, id value);


#line 32
@implementation ComGoogleGsonJsonObject


#line 37
- (ComGoogleGsonJsonObject *)deepCopy {
  ComGoogleGsonJsonObject *result = new_ComGoogleGsonJsonObject_init();
  for (id<JavaUtilMap_Entry> __strong entry_ in nil_chk([((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) entrySet])) {
    [result addWithNSString:[((id<JavaUtilMap_Entry>) nil_chk(entry_)) getKey] withComGoogleGsonJsonElement:[((ComGoogleGsonJsonElement *) nil_chk([entry_ getValue])) deepCopy]];
  }
  return result;
}


#line 53
- (void)addWithNSString:(NSString *)property
withComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)value {
  if (value == nil) {
    value = ComGoogleGsonJsonNull_get_INSTANCE_();
  }
  (void) [((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) putWithId:property withId:value];
}


#line 67
- (ComGoogleGsonJsonElement *)removeWithNSString:(NSString *)property {
  return [((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) removeWithId:property];
}


#line 78
- (void)addPropertyWithNSString:(NSString *)property
                   withNSString:(NSString *)value {
  [self addWithNSString:property withComGoogleGsonJsonElement:ComGoogleGsonJsonObject_createJsonElementWithId_(self, value)];
}


#line 89
- (void)addPropertyWithNSString:(NSString *)property
                   withNSNumber:(NSNumber *)value {
  [self addWithNSString:property withComGoogleGsonJsonElement:ComGoogleGsonJsonObject_createJsonElementWithId_(self, value)];
}


#line 100
- (void)addPropertyWithNSString:(NSString *)property
            withJavaLangBoolean:(JavaLangBoolean *)value {
  [self addWithNSString:property withComGoogleGsonJsonElement:ComGoogleGsonJsonObject_createJsonElementWithId_(self, value)];
}


#line 111
- (void)addPropertyWithNSString:(NSString *)property
          withJavaLangCharacter:(JavaLangCharacter *)value {
  [self addWithNSString:property withComGoogleGsonJsonElement:ComGoogleGsonJsonObject_createJsonElementWithId_(self, value)];
}


#line 121
- (ComGoogleGsonJsonElement *)createJsonElementWithId:(id)value {
  return ComGoogleGsonJsonObject_createJsonElementWithId_(self, value);
}


#line 131
- (id<JavaUtilSet>)entrySet {
  return [((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) entrySet];
}


#line 141
- (jboolean)hasWithNSString:(NSString *)memberName {
  return [((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) containsKeyWithId:memberName];
}


#line 151
- (ComGoogleGsonJsonElement *)getWithNSString:(NSString *)memberName {
  return [((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) getWithId:memberName];
}


#line 161
- (ComGoogleGsonJsonPrimitive *)getAsJsonPrimitiveWithNSString:(NSString *)memberName {
  return (ComGoogleGsonJsonPrimitive *) check_class_cast([((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) getWithId:memberName], [ComGoogleGsonJsonPrimitive class]);
}


#line 171
- (ComGoogleGsonJsonArray *)getAsJsonArrayWithNSString:(NSString *)memberName {
  return (ComGoogleGsonJsonArray *) check_class_cast([((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) getWithId:memberName], [ComGoogleGsonJsonArray class]);
}


#line 181
- (ComGoogleGsonJsonObject *)getAsJsonObjectWithNSString:(NSString *)memberName {
  return (ComGoogleGsonJsonObject *) check_class_cast([((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) getWithId:memberName], [ComGoogleGsonJsonObject class]);
}


#line 186
- (jboolean)isEqual:(id)o {
  return (o == self) || ([o isKindOfClass:[ComGoogleGsonJsonObject class]] &&
#line 188
  [((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(((ComGoogleGsonJsonObject *) nil_chk(((ComGoogleGsonJsonObject *) check_class_cast(o, [ComGoogleGsonJsonObject class]))))->members_)) isEqual:members_]);
}

- (NSUInteger)hash {
  return ((jint) [((ComGoogleGsonInternalLinkedTreeMap *) nil_chk(members_)) hash]);
}

- (instancetype)init {
  ComGoogleGsonJsonObject_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "deepCopy", NULL, "Lcom.google.gson.JsonObject;", 0x0, NULL, NULL },
    { "addWithNSString:withComGoogleGsonJsonElement:", "add", "V", 0x1, NULL, NULL },
    { "removeWithNSString:", "remove", "Lcom.google.gson.JsonElement;", 0x1, NULL, NULL },
    { "addPropertyWithNSString:withNSString:", "addProperty", "V", 0x1, NULL, NULL },
    { "addPropertyWithNSString:withNSNumber:", "addProperty", "V", 0x1, NULL, NULL },
    { "addPropertyWithNSString:withJavaLangBoolean:", "addProperty", "V", 0x1, NULL, NULL },
    { "addPropertyWithNSString:withJavaLangCharacter:", "addProperty", "V", 0x1, NULL, NULL },
    { "createJsonElementWithId:", "createJsonElement", "Lcom.google.gson.JsonElement;", 0x2, NULL, NULL },
    { "entrySet", NULL, "Ljava.util.Set;", 0x1, NULL, NULL },
    { "hasWithNSString:", "has", "Z", 0x1, NULL, NULL },
    { "getWithNSString:", "get", "Lcom.google.gson.JsonElement;", 0x1, NULL, NULL },
    { "getAsJsonPrimitiveWithNSString:", "getAsJsonPrimitive", "Lcom.google.gson.JsonPrimitive;", 0x1, NULL, NULL },
    { "getAsJsonArrayWithNSString:", "getAsJsonArray", "Lcom.google.gson.JsonArray;", 0x1, NULL, NULL },
    { "getAsJsonObjectWithNSString:", "getAsJsonObject", "Lcom.google.gson.JsonObject;", 0x1, NULL, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL, NULL },
    { "hash", "hashCode", "I", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "members_", NULL, 0x12, "Lcom.google.gson.internal.LinkedTreeMap;", NULL, "Lcom/google/gson/internal/LinkedTreeMap<Ljava/lang/String;Lcom/google/gson/JsonElement;>;",  },
  };
  static const J2ObjcClassInfo _ComGoogleGsonJsonObject = { 2, "JsonObject", "com.google.gson", NULL, 0x11, 17, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonJsonObject;
}

@end


#line 121
ComGoogleGsonJsonElement *ComGoogleGsonJsonObject_createJsonElementWithId_(ComGoogleGsonJsonObject *self, id value) {
  return value == nil ? ComGoogleGsonJsonNull_get_INSTANCE_() : new_ComGoogleGsonJsonPrimitive_initWithId_(value);
}

void ComGoogleGsonJsonObject_init(ComGoogleGsonJsonObject *self) {
  (void) ComGoogleGsonJsonElement_init(self);
  self->members_ = new_ComGoogleGsonInternalLinkedTreeMap_init();
}

ComGoogleGsonJsonObject *new_ComGoogleGsonJsonObject_init() {
  ComGoogleGsonJsonObject *self = [ComGoogleGsonJsonObject alloc];
  ComGoogleGsonJsonObject_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonJsonObject)
