//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/JsonSerializationContext.java
//

#ifndef _ComGoogleGsonJsonSerializationContext_H_
#define _ComGoogleGsonJsonSerializationContext_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonJsonElement;
@protocol JavaLangReflectType;

/**
 @brief Context for serialization that is passed to a custom serializer during invocation of its JsonSerializer#serialize(Object,Type,JsonSerializationContext) method.
 @author Inderjeet Singh
 @author Joel Leitch
 */
@protocol ComGoogleGsonJsonSerializationContext < NSObject, JavaObject >

/**
 @brief Invokes default serialization on the specified object.
 @param src the object that needs to be serialized.
 @return a tree of JsonElement s corresponding to the serialized form of <code>src</code> .
 */
- (ComGoogleGsonJsonElement *)serializeWithId:(id)src;

/**
 @brief Invokes default serialization on the specified object passing the specific type information.
 It should never be invoked on the element received as a parameter of the JsonSerializer#serialize(Object,Type,JsonSerializationContext) method. Doing so will result in an infinite loop since Gson will in-turn call the custom serializer again.
 @param src the object that needs to be serialized.
 @param typeOfSrc the actual genericized type of src object.
 @return a tree of JsonElement s corresponding to the serialized form of <code>src</code> .
 */
- (ComGoogleGsonJsonElement *)serializeWithId:(id)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonSerializationContext)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonSerializationContext)

#endif // _ComGoogleGsonJsonSerializationContext_H_
