//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/internal/LazilyParsedNumber.java
//


#line 1 "jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/internal/LazilyParsedNumber.java"

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "LazilyParsedNumber.h"
#include "java/io/ObjectStreamException.h"
#include "java/lang/Double.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/NumberFormatException.h"
#include "java/math/BigDecimal.h"

@interface ComGoogleGsonInternalLazilyParsedNumber () {
 @public
  NSString *value_;
}

/**
 @brief If somebody is unlucky enough to have to serialize one of these, serialize it as a BigDecimal so that they won't need Gson on the other side to deserialize it.
 */
- (id)writeReplace;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLazilyParsedNumber, value_, NSString *)


#line 26
@implementation ComGoogleGsonInternalLazilyParsedNumber


#line 29
- (instancetype)initWithNSString:(NSString *)value {
  ComGoogleGsonInternalLazilyParsedNumber_initWithNSString_(self, value);
  return self;
}

- (jint)intValue {
  @try {
    return JavaLangInteger_parseIntWithNSString_(value_);
  }
  @catch (
#line 37
  JavaLangNumberFormatException *e) {
    @try {
      return (jint) JavaLangLong_parseLongWithNSString_(value_);
    }
    @catch (
#line 40
    JavaLangNumberFormatException *nfe) {
      return [new_JavaMathBigDecimal_initWithNSString_(value_) intValue];
    }
  }
}


#line 47
- (jlong)longLongValue {
  @try {
    return JavaLangLong_parseLongWithNSString_(value_);
  }
  @catch (
#line 50
  JavaLangNumberFormatException *e) {
    return [new_JavaMathBigDecimal_initWithNSString_(value_) longLongValue];
  }
}


#line 56
- (jfloat)floatValue {
  return JavaLangFloat_parseFloatWithNSString_(value_);
}


#line 61
- (jdouble)doubleValue {
  return JavaLangDouble_parseDoubleWithNSString_(value_);
}


#line 66
- (NSString *)description {
  return value_;
}


#line 75
- (id)writeReplace {
  return new_JavaMathBigDecimal_initWithNSString_(value_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "LazilyParsedNumber", NULL, 0x1, NULL, NULL },
    { "intValue", NULL, "I", 0x1, NULL, NULL },
    { "longLongValue", "longValue", "J", 0x1, NULL, NULL },
    { "floatValue", NULL, "F", 0x1, NULL, NULL },
    { "doubleValue", NULL, "D", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "writeReplace", NULL, "Ljava.lang.Object;", 0x2, "Ljava.io.ObjectStreamException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "value_", NULL, 0x12, "Ljava.lang.String;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLazilyParsedNumber = { 2, "LazilyParsedNumber", "com.google.gson.internal", NULL, 0x11, 7, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonInternalLazilyParsedNumber;
}

@end


#line 29
void ComGoogleGsonInternalLazilyParsedNumber_initWithNSString_(ComGoogleGsonInternalLazilyParsedNumber *self, NSString *value) {
  (void) NSNumber_init(self);
  
#line 30
  self->value_ = value;
}


#line 29
ComGoogleGsonInternalLazilyParsedNumber *new_ComGoogleGsonInternalLazilyParsedNumber_initWithNSString_(NSString *value) {
  ComGoogleGsonInternalLazilyParsedNumber *self = [ComGoogleGsonInternalLazilyParsedNumber alloc];
  ComGoogleGsonInternalLazilyParsedNumber_initWithNSString_(self, value);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLazilyParsedNumber)
