//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/internal/ObjectConstructor.java
//


#line 1 "jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/internal/ObjectConstructor.java"

#include "J2ObjC_source.h"
#include "ObjectConstructor.h"

@interface ComGoogleGsonInternalObjectConstructor : NSObject
@end


#line 27
@implementation ComGoogleGsonInternalObjectConstructor

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "construct", NULL, "TT;", 0x401, NULL, "()TT;" },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalObjectConstructor = { 2, "ObjectConstructor", "com.google.gson.internal", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_ComGoogleGsonInternalObjectConstructor;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalObjectConstructor)
