//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/annotations/SerializedName.java
//

#ifndef _ComGoogleGsonAnnotationsSerializedName_H_
#define _ComGoogleGsonAnnotationsSerializedName_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

/**
 @brief An annotation that indicates this member should be serialized to JSON with the provided name value as its field name.
 <p>This annotation will override any com.google.gson.FieldNamingPolicy , including the default field naming policy, that may have been set on the com.google.gson.Gson instance.  A different naming policy can set using the <code>GsonBuilder</code> class.  See com.google.gson.GsonBuilder#setFieldNamingPolicy(com.google.gson.FieldNamingPolicy) for more information.</p> <p>Here is an example of how this annotation is meant to be used:</p> <pre> public class SomeClassWithFields { &#64SerializedName("name") private final String someField; private final String someOtherField; public SomeClassWithFields(String a, String b) { this.someField = a; this.someOtherField = b; } } </pre> <p>The following shows the output that is generated when serializing an instance of the above example class:</p> <pre> SomeClassWithFields objectToSerialize = new SomeClassWithFields("a", "b"); Gson gson = new Gson(); String jsonRepresentation = gson.toJson(objectToSerialize); System.out.println(jsonRepresentation); ===== OUTPUT ===== {"name":"a","someOtherField":"b"} </pre> <p>NOTE: The value you specify in this annotation must be a valid JSON field name.</p>
 @author Inderjeet Singh
 @author Joel Leitch
 */
@protocol ComGoogleGsonAnnotationsSerializedName < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

@end

@interface ComGoogleGsonAnnotationsSerializedName : NSObject < ComGoogleGsonAnnotationsSerializedName > {
 @private
  NSString *value_;
}

- (instancetype)initWithValue:(NSString *)value__;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonAnnotationsSerializedName)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonAnnotationsSerializedName)

#endif // _ComGoogleGsonAnnotationsSerializedName_H_
