//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/metcalfe/service/SimpleHttpClient.java
//

#ifndef _SimpleHttpClient_H_
#define _SimpleHttpClient_H_

#include "HttpClient.h"
#include "J2ObjC_header.h"

@class JavaIoInputStream;

/**
 @brief Created by alex on 12/07/15.
 */
@interface SimpleHttpClient : NSObject < HttpClient >

#pragma mark Public

- (instancetype)init;

- (NSString *)performGetWithNSString:(NSString *)getUrl;

- (NSString *)readItWithJavaIoInputStream:(JavaIoInputStream *)stream;

@end

J2OBJC_EMPTY_STATIC_INIT(SimpleHttpClient)

FOUNDATION_EXPORT void SimpleHttpClient_init(SimpleHttpClient *self);

FOUNDATION_EXPORT SimpleHttpClient *new_SimpleHttpClient_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(SimpleHttpClient)

typedef SimpleHttpClient ComMetcalfeServiceSimpleHttpClient;

#endif // _SimpleHttpClient_H_
