//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/annotations/Since.java
//

#ifndef _ComGoogleGsonAnnotationsSince_H_
#define _ComGoogleGsonAnnotationsSince_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

/**
 @brief An annotation that indicates the version number since a member or a type has been present.
 This annotation is useful to manage versioning of your Json classes for a web-service. <p> This annotation has no effect unless you build com.google.gson.Gson with a com.google.gson.GsonBuilder and invoke com.google.gson.GsonBuilder#setVersion(double) method. <p>Here is an example of how this annotation is meant to be used:</p> <pre> public class User { private String firstName; private String lastName; &#64Since(1.0) private String emailAddress; &#64Since(1.0) private String password; &#64Since(1.1) private Address address; } </pre> <p>If you created Gson with <code>new Gson()</code> , the <code>toJson()</code> and <code>fromJson()</code> methods will use all the fields for serialization and deserialization. However, if you created Gson with <code>Gson gson = new GsonBuilder().setVersion(1.0).create()</code> then the <code>toJson()</code> and <code>fromJson()</code> methods of Gson will exclude the <code>address</code> field since it's version number is set to <code>1.1</code> .</p>
 @author Inderjeet Singh
 @author Joel Leitch
 */
@protocol ComGoogleGsonAnnotationsSince < JavaLangAnnotationAnnotation >

@property (readonly) jdouble value;

@end

@interface ComGoogleGsonAnnotationsSince : NSObject < ComGoogleGsonAnnotationsSince > {
 @private
  jdouble value_;
}

- (instancetype)initWithValue:(jdouble)value__;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonAnnotationsSince)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonAnnotationsSince)

#endif // _ComGoogleGsonAnnotationsSince_H_
