//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/gson-2.3.1-sources.jar!com/google/gson/annotations/Until.java
//

#ifndef _ComGoogleGsonAnnotationsUntil_H_
#define _ComGoogleGsonAnnotationsUntil_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

/**
 @brief An annotation that indicates the version number until a member or a type should be present.
 Basically, if Gson is created with a version number that exceeds the value stored in the <code>Until</code> annotation then the field will be ignored from the JSON output.  This annotation is useful to manage versioning of your JSON classes for a web-service. <p> This annotation has no effect unless you build com.google.gson.Gson with a com.google.gson.GsonBuilder and invoke com.google.gson.GsonBuilder#setVersion(double) method. <p>Here is an example of how this annotation is meant to be used:</p> <pre> public class User { private String firstName; private String lastName; &#64Until(1.1) private String emailAddress; &#64Until(1.1) private String password; } </pre> <p>If you created Gson with <code>new Gson()</code> , the <code>toJson()</code> and <code>fromJson()</code> methods will use all the fields for serialization and deserialization. However, if you created Gson with <code>Gson gson = new GsonBuilder().setVersion(1.2).create()</code> then the <code>toJson()</code> and <code>fromJson()</code> methods of Gson will exclude the <code>emailAddress</code> and <code>password</code> fields from the example above, because the version number passed to the GsonBuilder, <code>1.2</code> , exceeds the version number set on the <code>Until</code> annotation, <code>1.1</code> , for those fields.
 @author Inderjeet Singh
 @author Joel Leitch
 @since 1.3
 */
@protocol ComGoogleGsonAnnotationsUntil < JavaLangAnnotationAnnotation >

@property (readonly) jdouble value;

@end

@interface ComGoogleGsonAnnotationsUntil : NSObject < ComGoogleGsonAnnotationsUntil > {
 @private
  jdouble value_;
}

- (instancetype)initWithValue:(jdouble)value__;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonAnnotationsUntil)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonAnnotationsUntil)

#endif // _ComGoogleGsonAnnotationsUntil_H_
