# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'gradleIos' do

pod 'j2objc-shared', :path => '/Users/alex/dev/projects/j2objc-contributors/shared/build'
end

target 'gradleIosTests' do

end
